## Le mappe del mondo, disegnate a lettere. Le legge [code]build_maps.gd[/code]
## per costruire le scene in [code]World/maps/[/code].
##
## [b]Le lettere del pavimento[/b] (attraversabili): [code].[/code] assi viola,
## [code]=[/code] velluto rosso, [code]_[/code] palco, [code]g[/code] linoleum,
## [code]m[/code] marmo, [code]c[/code] lastricato dipinto, [code]b[/code] velluto blu,
## [code]d[/code] assi scure, [code]o[/code] soglia di una porta, [code]~[/code] le
## [b]quinte[/b] (ritagli e vernice: qui si incontrano le comparse).
##
## [b]Le lettere dei muri[/b] (solidi): [code]#[/code] fondale, [code]C[/code] sipario,
## [code]M[/code] specchi, [code]K[/code] cielo di tela, [code]B[/code] sbarre,
## [code]h[/code] file di poltrone, [code]G[/code] muro dei corridoi, [code]E[/code] bordo
## del palco, [code]R[/code] mattoni, spazio = il vuoto dietro le scene.
##
## Ogni altra lettera e' nella [code]legend[/code] della mappa: oggetti, bauli,
## boss, porte, punti d'arrivo. [code]decor[/code] sono oggetti appesi ai muri.
## [code]on[/code] dice quale pavimento mettere sotto una lettera (se no quello
## della mappa).
class_name MapLayouts extends RefCounted


static func all() -> Array[Dictionary]:
	return [
		{
			"id": "camerino", "floor": ".", "ambient": Color(0.78, 0.74, 0.76), "dust": true,
			"rows": [
				"##################",
				"##################",
				"#....L.....S.....#",
				"#...z...=........#",
				"#..k....=.....q..#",
				"#.......=........#",
				"#.......=........#",
				"#..a....=......p.#",
				"#.......=........#",
				"#.......@....n...#",
				"#................#",
				"#.......1........#",
				"##################",
			],
			"on": {"1": "o"},
			"legend": {
				"z": [{"t": "spawn", "id": "letto", "face": Vector2(0, 1)}],
				"L": [{"t": "prop", "kind": "letto"}, {"t": "inspect", "prompt": "Riposa", "heals": true, "radius": 30, "lines": ["Il tuo letto. Le lenzuola sono stirate come se nessuno ci avesse mai dormito."]}],
				"S": [{"t": "prop", "kind": "specchio"}, {"t": "inspect", "prompt": "Guarda", "lines": ["Lo specchio rotto. Le schegge sono ancora dentro la cornice.", "Ti guardi. Dove dovrebbe esserci una faccia, c'e' l'ovale liscio di chi non ha una parte.\n\nNon e' una ferita. E' che nessuno ne ha scritto una."]}],
				"k": [{"t": "chest", "kind": "scena"}],
				"q": [{"t": "prop", "kind": "cassettone"}],
				"a": [{"t": "prop", "kind": "sedia"}],
				"p": [{"t": "prop", "kind": "pianta"}],
				"n": [{"t": "inspect", "prompt": "Leggi", "lines": ["Accanto alla porta, inciso nel muro: [b]%d[/b].\n\nNon ricordi di averlo fatto. Ma la mano e' la tua."]}],
				"@": [{"t": "spawn", "id": "ingresso", "face": Vector2(0, -1)}],
				"1": [{"t": "warp", "to": "piazza", "spawn": "ingresso", "size": Vector2(32, 32)}],
			},
			"decor": [{"t": "prop", "kind": "quadro", "at": Vector2(3, 1)}, {"t": "prop", "kind": "locandina", "at": Vector2(14, 1)}],
		},
		{
			"id": "piazza", "floor": "c", "ambient": Color(0.78, 0.7, 0.92), "dust": true,
			"rows": [
				"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
				"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
				"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
				"#ccccccccccccccccccccccccccccccccccc####",
				"#cccccccccccccccccccccccccccccccctcc####",
				"#ccccccccccccccccccccccccccccccccccc####",
				"#cccFcccccfcccccecccccFcccccfccccccc####",
				"#ccccccccccccccccccccccccccccccccccc####",
				"#cccccc!ccccc!ccccc!ccccc!ccccc!cccc####",
				"#cccccccccccccccccccccccc~~~~~~~~ccc####",
				"#cccccccccccccccccccccccc~~~~~~~~ccc####",
				"#cccccccccccccccccccccccccccccccccccc###",
				"3rccccccc$cccc!ccccccccccccccccccccsZcc2",
				"#ccccccccccccccccccccccccccccccccccc####",
				"#ccccccccccccccccccccccccccccccccccc####",
				"#ccccc~~~~~~~~~cccccccccwccccccccccc####",
				"#ccccc~~~~~~~~~ccccccccccccccccccccc####",
				"#ccccc~~~~~~~~~ccccccccccccTcccccccc####",
				"#ccccc~~~~~~~~~ccccc#hhhhhhhhhhhhhh#####",
				"#ccccccccccccccccccc#dddddddddddddd#####",
				"#ccccccccccccccccccc#dAdddddddddddd#####",
				"#cclcccccccccccccccc#dddddddddddddd#####",
				"#ckccccNcccccccccccc#dddddddddddddd#####",
				"#ccccccccccccccccccc#dddddddddddddd#####",
				"#ddd@dddcccccccccccc#dddddddddddddd#####",
				"####1###################################",
			],
			"on": {"2": "o", "3": "o", "1": "o"},
			"legend": {
				"2": [{"t": "warp", "to": "galleria", "spawn": "ingresso", "size": Vector2(32, 32), "boss": "comparsa", "locked": "La Comparsa e' seduta davanti al passaggio. \"Meglio qui\", dice, e non si sposta."}],
				"Z": [{"t": "boss", "id": "comparsa", "face": Vector2(-1, 0), "sight": 5, "off": Vector2(0, -32), "tint": Color(0.72, 0.7, 0.72)}],
				"s": [{"t": "spawn", "id": "galleria", "face": Vector2(-1, 0)}],
				"3": [{"t": "warp", "to": "ridotto", "spawn": "ingresso", "size": Vector2(32, 32)}],
				"r": [{"t": "spawn", "id": "ridotto", "face": Vector2(1, 0)}],
				"1": [{"t": "warp", "to": "camerino", "spawn": "ingresso", "size": Vector2(32, 32)}],
				"@": [{"t": "spawn", "id": "ingresso", "face": Vector2(0, -1)}],
				"F": [{"t": "prop", "kind": "facciata"}],
				"f": [{"t": "prop", "kind": "facciata_b"}],
				"e": [{"t": "prop", "kind": "facciata_c"}],
				"!": [{"t": "prop", "kind": "lampione"}],
				"$": [{"t": "shop", "id": "burattinaio", "stall": "baracca"}],
				"l": [{"t": "prop", "kind": "lampione_spento"}],
				"k": [{"t": "chest", "kind": "scena"}],
				"t": [{"t": "chest", "kind": "cassa", "money": 40}],
				"N": [{"t": "npc", "name": "Il Macchinista", "look": "npc", "tint": Color(0.9, 0.85, 1.0), "face": Vector2(1, 0), "lines": ["Sei quello senza faccia, eh? Benvenuto in piazza. E' tutta dipinta: non appoggiarti ai palazzi.", "Dove il pavimento e' pieno di ritagli e vernice, nelle quinte, ci si imbatte in qualcuno. Comparse, macchie che si staccano dai fondali. Si recita, si vince qualche biglietto.", "I biglietti li spendi alla baracca del Burattinaio. E se ti senti a pezzi, nel tuo camerino c'e' il letto. Lo sanno tutti: il letto del camerino rimette in piedi."]}],
				"w": [{"t": "slime"}],
				"A": [{"t": "audience", "rows": 2, "seats": 10, "face": Vector2(0, -1), "aisle": 5, "spacing": Vector2(36, 40)}],
				"T": [{"t": "trigger", "event": "platea", "size": Vector2(320, 32)}],
			},
			"decor": [],
		},
		{
			"id": "ridotto", "floor": "b", "ambient": Color(0.85, 0.72, 0.72), "dust": true,
			"rows": [
				"########################",
				"########################",
				"#bbbbbbbbbbbbbbbbbbbbbb#",
				"#b.RRRRRRRR..........pb#",
				"#bbbbbNbbbbbbbbbbbbbbbb#",
				"#bbbbbbbbbbbbbbb$bbbbbb#",
				"#bpbbbbbbbbbbbbbbbbbbbb#",
				"#bbbbbbbbbbbbbbbbbbbbb@1",
				"#bbbbbbbbbbbbnbbbbbbbbb#",
				"#bbbabbabbbbbbbbbbbbbbb#",
				"#bbbbbbbbbbbbbbbbbbbbbb#",
				"#bbbbbbbbbbbbbbbbbbbbbb#",
				"#bbbabbabbbbSbbbbbbtbbb#",
				"#bbbbbbbbbbbbbbbbbbbbbb#",
				"########################",
			],
			"on": {"1": "o"},
			"legend": {
				"1": [{"t": "warp", "to": "piazza", "spawn": "ridotto", "size": Vector2(32, 32)}],
				"@": [{"t": "spawn", "id": "ingresso", "face": Vector2(-1, 0)}],
				"N": [{"t": "npc", "name": "Il Barista", "look": "mc", "tint": Color(0.95, 0.8, 0.6), "face": Vector2(0, 1), "heals": true, "lines": ["\"Un caffe' di scena? Non e' caffe', e' acqua colorata. Ma funziona lo stesso: e' teatro.\""]}],
				"$": [{"t": "shop", "id": "bigliettaia", "stall": "pannello_rosso", "keeper": "npc", "keeper_tint": Color(1.0, 0.85, 0.9)}],
				"a": [{"t": "prop", "kind": "sedia"}],
				"p": [{"t": "prop", "kind": "pianta"}],
				"S": [{"t": "prop", "kind": "specchio"}],
				"t": [{"t": "chest", "kind": "cassa", "money": 60, "item": "te_caldo"}],
				"n": [{"t": "npc", "name": "Una spettatrice", "look": "npc", "tint": Color(0.8, 0.9, 1.0), "face": Vector2(-1, 0), "wander": true, "lines": ["\"Il secondo atto e' cominciato da un pezzo. O forse e' il primo. Io sono uscita a prendere aria e non ritrovo il mio posto.\"", "\"Si dice che in fondo alla platea ci sia un manichino che cambia posto. Sciocchezze. I manichini non si muovono.\""]}],
			},
			"decor": [{"t": "prop", "kind": "locandina", "at": Vector2(16, 1)}, {"t": "prop", "kind": "quadro", "at": Vector2(9, 2)}],
		},
		{
			"id": "galleria", "floor": "m", "ambient": Color(0.66, 0.72, 0.95), "dust": true,
			"rows": [
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
				"MMMMMMMMMMMMMMMMM3MMMMMMMMMMMMMMMMMM",
				"MmmmmmmmmmmmmmmmmrmmmmmmmmmmmmmmMMMM",
				"Mmmtmmmm~~~~~~mmmmmmmmmmmmmmmkmmMMMM",
				"Mmmmmmmm~~~~~~mmmmmmmmmmmmmmmmmmMMMM",
				"MmmmmMMm~~~~~~mmmmmmmmmMMmmmMMmmMMMM",
				"MmmmmmmmmmmmmmSmmmmmSmmmmmmmmmmmMMMM",
				"MmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmMMMM",
				"MmmmmmmmmmmmmmmmmmmmmmmmmmSmmmmmMMMM",
				"MmmmmMMmmmmMMmmmmmmmNmmMMmmmMMmmMMMM",
				"MmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmMMM",
				"1@mmmmmmSmmmmmmmmmmmmmmmmmmmmmmsZmm2",
				"MmmmmmmmmmmmmmSmmmmmSmmmmmmmmmmmMMMM",
				"MmmmmMMmmmmMMmmmmmmmmmmMMmmmMMmmMMMM",
				"MmmmmmmTmmmmmmmmmmmmmmmmmmmmmmmmMMMM",
				"MhhhhhhhhhhhhhMmmmmmmmmmmmmmmmmmMMMM",
				"MdddddddddddddMmmmmmmmmmmmmmmmmmMMMM",
				"MdAdddddddddddMmmm~~~~~~~~~mmmmmMMMM",
				"MdddddddddddddMmmm~~~~~~~~~mmmmmMMMM",
				"MdddddddddddddMmmm~~~~~~~~~mmmmmMMMM",
				"MdddddddddddddMmmmmmmmmmmmmmmmmmMMMM",
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
			],
			"on": {"2": "o", "1": "o", "3": "o"},
			"legend": {
				"2": [{"t": "warp", "to": "palco", "spawn": "ingresso", "size": Vector2(32, 32), "boss": "sostituto", "locked": "Il Sostituto ti sbarra la strada. Ha la tua faccia, cioe' nessuna."}],
				"Z": [{"t": "boss", "id": "sostituto", "face": Vector2(-1, 0), "sight": 5, "off": Vector2(0, -32), "tint": Color(0.9, 0.92, 1.0)}],
				"s": [{"t": "spawn", "id": "palco", "face": Vector2(-1, 0)}],
				"1": [{"t": "warp", "to": "piazza", "spawn": "galleria", "size": Vector2(32, 32)}],
				"@": [{"t": "spawn", "id": "ingresso", "face": Vector2(1, 0)}],
				"3": [{"t": "warp", "to": "magazzino", "spawn": "ingresso", "size": Vector2(32, 32)}],
				"r": [{"t": "spawn", "id": "magazzino", "face": Vector2(0, 1)}],
				"S": [{"t": "prop", "kind": "specchio"}],
				"A": [{"t": "audience", "rows": 2, "seats": 8, "face": Vector2(0, -1), "aisle": 4, "spacing": Vector2(36, 40)}],
				"T": [{"t": "trigger", "event": "platea", "size": Vector2(320, 32)}],
				"k": [{"t": "chest", "kind": "scena"}],
				"t": [{"t": "chest", "kind": "cassa", "item": "te_caldo", "money": 20}],
				"N": [{"t": "npc", "name": "Un riflesso", "look": "mc", "tint": Color(0.75, 0.85, 1.0), "face": Vector2(0, 1), "lines": ["Il riflesso ti fa un cenno, un attimo prima che tu lo faccia a lui.", "\"Lui gioca le tue carte\", sussurra. \"Tutte. Se cambi repertorio prima di affrontarlo, cambia anche lui. Ma la maschera... quella la sceglie da te.\""]}],
			},
			"decor": [],
		},
		{
			"id": "magazzino", "floor": ".", "ambient": Color(0.62, 0.6, 0.7), "dust": true,
			"rows": [
				"RRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
				"RRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
				"R............................R",
				"R.t........................u.R",
				"R...x....x...Q...Q..x....x...R",
				"R..........~~~~~~~~..........R",
				"R..........~~~~~~~~..........R",
				"R...x....x.~~~~~~~~.x....x...R",
				"R..........~~~~~~~~..........R",
				"R..............v.............R",
				"R...x....x..........x....x...R",
				"R............................R",
				"R....~~~~~~~~.....~~~~~~~~...R",
				"R.Q..~~~~~~~~.....~~~~~~~~.Q.R",
				"R....~~~~~~~~.....~~~~~~~~...R",
				"R......N.....................R",
				"R..............@.............R",
				"RRRRRRRRRRRRRRR1RRRRRRRRRRRRRR",
			],
			"on": {"1": "o"},
			"legend": {
				"1": [{"t": "warp", "to": "galleria", "spawn": "magazzino", "size": Vector2(32, 32)}],
				"@": [{"t": "spawn", "id": "ingresso", "face": Vector2(0, -1)}],
				"x": [{"t": "prop", "kind": "cassa"}],
				"Q": [{"t": "prop", "kind": "quinta"}],
				"t": [{"t": "chest", "kind": "cassa", "money": 70, "card": "lightning_charge"}],
				"u": [{"t": "chest", "kind": "cassa", "item": "mazzo_di_fiori", "money": 30}],
				"v": [{"t": "chest", "kind": "cassa", "item": "camomilla"}],
				"N": [{"t": "npc", "name": "Il Magazziniere", "look": "npc", "tint": Color(0.8, 0.75, 0.65), "face": Vector2(1, 0), "lines": ["\"Attento ai manichini da prova. Quelli del laboratorio. Non sono come quelli della platea: quelli si muovono, e recitano pure male.\""]}],
			},
			"decor": [{"t": "prop", "kind": "locandina", "at": Vector2(6, 1)}, {"t": "prop", "kind": "locandina", "at": Vector2(22, 1)}],
		},
		{
			"id": "palco", "floor": "_", "ambient": Color(0.95, 0.78, 0.62), "dust": true,
			"rows": [
				"CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
				"CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
				"CC3CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
				"#_r__________________________________#",
				"#_____*________________________*_____#",
				"#____________________________________#",
				"#__________________Z________________s2",
				"#____________________________________#",
				"#____Q__________________________Q____#",
				"#__k_________________________________#",
				"#____________________________________#",
				"#__________Nj________________________#",
				"#__________________T_________________#",
				"#E__EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE__E#",
				"#ddd==============================ddd#",
				"#dddddddddddddddddddddddddddddddddddd#",
				"#ddddAddddddddddddddddddddddddddddddd#",
				"#dddddddddddddddddddddddddddddddddddd#",
				"#dddddddddddddddddddddddddddddddddddd#",
				"#dddddddddddddddddddddddddddddddddddd#",
				"#dddddddddddddddddddddddddddddddddddd#",
				"#dddddddddddddddddddddddddddddddddddd#",
				"#ddddddddddddddddddddddddddddddddddtd#",
				"#d@dddddddddddddddddddddddddddddddddd#",
				"##1###################################",
			],
			"on": {"2": "o", "3": "o", "1": "o"},
			"legend": {
				"2": [{"t": "warp", "to": "corridoi", "spawn": "ingresso", "size": Vector2(32, 32), "boss": "prima_attrice", "locked": "Le quinte di destra sono chiuse. Finche' la Prima Attrice e' in scena, nessuno esce dal palco."}],
				"s": [{"t": "spawn", "id": "corridoi", "face": Vector2(-1, 0)}],
				"3": [{"t": "warp", "to": "graticcia", "spawn": "ingresso", "size": Vector2(32, 32)}],
				"r": [{"t": "spawn", "id": "graticcia", "face": Vector2(0, 1)}],
				"1": [{"t": "warp", "to": "galleria", "spawn": "palco", "size": Vector2(32, 32)}],
				"@": [{"t": "spawn", "id": "ingresso", "face": Vector2(0, -1)}],
				"Z": [{"t": "boss", "id": "prima_attrice", "face": Vector2(0, 1), "sight": 4, "off": Vector2(64, -32), "tint": Color(1.0, 0.82, 0.78)}],
				"*": [{"t": "prop", "kind": "riflettore"}],
				"Q": [{"t": "prop", "kind": "quinta"}],
				"k": [{"t": "chest", "kind": "scena"}],
				"N": [{"t": "npc", "name": "Il Suggeritore", "look": "mc", "tint": Color(0.7, 0.7, 0.6), "face": Vector2(0, 1), "lines": ["\"Psst. La battuta e': non correre. Lei ti toglie la voce: Panico di scena, tanto. Tieni del Favore da parte, e scegli una maschera che perdona.\"", "\"E se ti serve, in graticcia, sopra le corde, c'e' un baule che nessuno ricorda di aver lasciato.\""]}],
				"j": [{"t": "prop", "kind": "leggio"}],
				"A": [{"t": "audience", "rows": 3, "seats": 14, "face": Vector2(0, -1), "aisle": 7, "spacing": Vector2(36, 40)}],
				"T": [{"t": "trigger", "event": "platea", "size": Vector2(480, 32)}],
				"t": [{"t": "chest", "kind": "cassa", "money": 90}],
			},
			"decor": [],
		},
		{
			"id": "graticcia", "floor": "d", "ambient": Color(0.55, 0.5, 0.65), "dust": true,
			"rows": [
				"##################################",
				"##################################",
				"#                                #",
				"#....~~~~~~.....................k#",
				"#....~~~~~~.............*...N....#",
				"#..            ...             ..#",
				"#..            ~~~             ..#",
				"#..            ~~~             ..#",
				"#..            ~~~             ..#",
				"#..            ~~~             ..#",
				"#..            ...             ..#",
				"#..            .*.             ..#",
				"#..@................~~~~~~~~.....#",
				"#.1.....*...........~~~~~~~~...t.#",
				"##################################",
			],
			"on": {"1": "."},
			"legend": {
				"1": [{"t": "warp", "to": "palco", "spawn": "graticcia", "size": Vector2(32, 32)}],
				"@": [{"t": "spawn", "id": "ingresso", "face": Vector2(1, 0)}],
				"*": [{"t": "prop", "kind": "riflettore"}],
				"k": [{"t": "chest", "kind": "scena"}],
				"t": [{"t": "chest", "kind": "cassa", "money": 120, "item": "camomilla"}],
				"N": [{"t": "npc", "name": "Il Tecnico delle Luci", "look": "npc", "tint": Color(0.75, 0.95, 0.8), "face": Vector2(-1, 0), "lines": ["\"Da quassu' si vede chi recita e chi fa finta. Tu fai finta bene.\"", "\"Un consiglio: la gabbia del Carceriere ti toglie pubblico a ogni turno. Battute che costano poco, e niente fretta.\""]}],
			},
			"decor": [],
		},
		{
			"id": "corridoi", "floor": "g", "ambient": Color(0.7, 0.85, 0.68), "dust": true,
			"rows": [
				"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
				"GGGGGGGGGGGGGG3GGGGGGGGGGGGGGGGGGGGGGGGGGG",
				"GggggDggggIgggrggggJggggLggggPgggggggggggG",
				"GggggggggggggggggggggggggggggggggggggggggG",
				"Ggggggggggggggggggggggggg~~~~~~~~ggggggggG",
				"1@ggggggggggggggggggggggg~~~~~~~~ggggggggG",
				"GgggggggggNgggggggggggggg~~~~~~~~ggggggggG",
				"GggggggggggggggggggggggggggggggggggggggggG",
				"GggggggggggggggggggggggggggggggggggggggggG",
				"GGGGGGggGGGGGGGGGGGGggGGGGGGGGGGGGGGGGGGGG",
				"GGGGGGggGGGGGGGGGGGGggGGGGGGGGGGGGGGGGGGGG",
				"GgggggggggggggggggggTgggggggggggggBBBBBBBG",
				"GgggggggggggggGhhhhhhhhhhhhGggggggB.....BG",
				"Gggg~~~~~~~~~~GddddddddddddGggggggB.....BG",
				"Gggg~~~~~~~~~~GdAddddddddddGgggggZg.....BG",
				"Gggg~~~~~~~~~~GddddddddddddG~~ggsgg......2",
				"GgggggggggggggGddddddddddddG~~ggggB.....BG",
				"GgtgggggggggggGddddddddddddGggggggB.....BG",
				"GgggggggggggggGggggggggggggGggggggBBBBBBBG",
				"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
			],
			"on": {"1": "o", "3": "o", "2": "o"},
			"legend": {
				"1": [{"t": "warp", "to": "palco", "spawn": "corridoi", "size": Vector2(32, 32)}],
				"@": [{"t": "spawn", "id": "ingresso", "face": Vector2(1, 0)}],
				"3": [{"t": "warp", "to": "sartoria", "spawn": "ingresso", "size": Vector2(32, 32)}],
				"r": [{"t": "spawn", "id": "sartoria", "face": Vector2(0, 1)}],
				"2": [{"t": "warp", "to": "auditorium", "spawn": "ingresso", "size": Vector2(32, 32), "boss": "carceriere", "locked": "La gabbia e' chiusa. Il Carceriere ha le chiavi alla cintura."}],
				"Z": [{"t": "boss", "id": "carceriere", "face": Vector2(-1, 0), "sight": 6, "off": Vector2(0, -64), "tint": Color(0.72, 0.88, 0.72)}],
				"s": [{"t": "spawn", "id": "auditorium", "face": Vector2(-1, 0)}],
				"D": [{"t": "inspect", "prompt": "Leggi", "lines": ["Una targhetta sulla porta: [i]Primo Attore[/i]. Dentro, silenzio."]}],
				"I": [{"t": "inspect", "prompt": "Leggi", "lines": ["Targhetta: [i]Il Coro[/i]. Dietro la porta, cento voci provano la stessa battuta."]}],
				"J": [{"t": "inspect", "prompt": "Leggi", "lines": ["Targhetta: [i]Comparse[/i]. La porta e' socchiusa. Dentro, sedie vuote e un cartello: TORNIAMO SUBITO."]}],
				"L": [{"t": "inspect", "prompt": "Leggi", "lines": ["Targhetta: [i]Direzione[/i]. Chiusa a chiave. Da sotto la porta esce luce viola."]}],
				"P": [{"t": "inspect", "prompt": "Leggi", "lines": ["Targhetta: [i]?[/i]. Il nome e' stato grattato via. Ti sembra di riconoscere la calligrafia."]}],
				"t": [{"t": "chest", "kind": "cassa", "money": 80, "item": "te_caldo"}],
				"N": [{"t": "npc", "name": "Una maschera di sala", "look": "npc", "tint": Color(0.7, 0.9, 0.75), "face": Vector2(0, 1), "wander": true, "lines": ["\"Personale soltanto. Ma tu non sei nessuno, quindi puoi passare.\"", "\"La sartoria e' su, la prima porta senza targhetta. La Guardarobiera vende di tutto, se paghi.\""]}],
				"A": [{"t": "audience", "rows": 2, "seats": 7, "face": Vector2(0, -1), "aisle": 0, "spacing": Vector2(36, 40)}],
				"T": [{"t": "trigger", "event": "platea", "size": Vector2(288, 32)}],
			},
			"decor": [],
		},
		{
			"id": "sartoria", "floor": ".", "ambient": Color(0.8, 0.72, 0.85), "dust": true,
			"rows": [
				"##########################",
				"##########################",
				"#........................#",
				"#.......................t#",
				"#............$...........#",
				"#........................#",
				"#........................#",
				"#..Q..Q..Q.......Q..Q..Q.#",
				"#........................#",
				"#........~~~~~~~~........#",
				"#........~~~~~~~~........#",
				"#..y...y.~~~~~~~~..y...y.#",
				"#........~~~~~~~~........#",
				"#........................#",
				"#............@...........#",
				"#############1############",
			],
			"on": {"1": "o"},
			"legend": {
				"1": [{"t": "warp", "to": "corridoi", "spawn": "sartoria", "size": Vector2(32, 32)}],
				"@": [{"t": "spawn", "id": "ingresso", "face": Vector2(0, -1)}],
				"$": [{"t": "shop", "id": "spaccio", "stall": "pannello_rosso", "keeper": "mc", "keeper_tint": Color(0.95, 0.75, 0.85)}],
				"Q": [{"t": "prop", "kind": "quinta", "tint": Color(0.9, 0.6, 0.7)}],
				"y": [{"t": "npc", "name": "Un manichino da sarto", "look": "manichino", "tint": Color(0.95, 0.85, 0.75), "face": Vector2(0, 1), "prompt": "Guarda", "lines": ["Un manichino da sarto, senza testa, con gli spilli ancora nel petto. Non e' del pubblico: questo e' solo un attaccapanni con le spalle."]}],
				"t": [{"t": "chest", "kind": "cassa", "money": 50, "card": "dark_sacrifice"}],
			},
			"decor": [{"t": "prop", "kind": "stendardo", "at": Vector2(5, 1)}, {"t": "prop", "kind": "stendardo", "at": Vector2(20, 1)}],
		},
		{
			"id": "auditorium", "floor": "d", "ambient": Color(0.58, 0.45, 0.78), "dust": true,
			"rows": [
				"CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
				"CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
				"CCCCCCCCCCCCCCCCCC2CCCCCCCCCCCCCCCCCC",
				"#_________________s_________________#",
				"#_____*_______________________*_____#",
				"#___________________________________#",
				"#EEEEEEEEEEEEEEEE===EEEEEEEEEEEEEEEE#",
				"#dddddddddddddddd===dddddddddddddddd#",
				"#ddAddddddddddddd===ddIddddddddddddd#",
				"#dddddddddddddddd===dddddddddddddddd#",
				"#dddddddddddddddd===dddddddddddddddd#",
				"#dddddddddddddddd===dddddddddddddddd#",
				"#dddddddddddddddd=Z=dddddddddddddddd#",
				"#dddddddddddddddd===dddddddddddddddd#",
				"#dddddddddddddddd===dddddddddddddddd#",
				"#dddddddddddddddd===dddddddddddddddd#",
				"#dddddddddddddddd===dddddddddddddddd#",
				"#ddJddddddddddddd===ddLddddddddddddd#",
				"#dddddddddddddddd===dddddddddddddddd#",
				"#dddddddddddddddd===dddddddddddddddd#",
				"#dddddddddddddddd===dddddddddddddddd#",
				"#dddddddddddddddd===dddddddddddddddd#",
				"#dddddddddddddddd===dddddddddddddddd#",
				"#dddddddddddddddd===dddddddddddddddd#",
				"#dddddddddddddddd===dddddddddddddddd#",
				"#dddddddddddddddd=T=dddddddddddddddd#",
				"#dddddddddddddddd===dddddddddddddddd#",
				"#tddddddddddddddd===dddddddddddddddd#",
				"#dddddddddddddddd=@=dddddddddddddddd#",
				"##################1##################",
			],
			"on": {"2": "o", "1": "o"},
			"legend": {
				"2": [{"t": "warp", "to": "fondo", "spawn": "ingresso", "size": Vector2(32, 32), "boss": "ultimo", "locked": "L'Ultimo sta in mezzo al corridoio. Non ti lascia passare, e non ti lascia solo."}],
				"s": [{"t": "spawn", "id": "fondo", "face": Vector2(0, 1)}],
				"1": [{"t": "warp", "to": "corridoi", "spawn": "auditorium", "size": Vector2(32, 32)}],
				"@": [{"t": "spawn", "id": "ingresso", "face": Vector2(0, -1)}],
				"Z": [{"t": "boss", "id": "ultimo", "face": Vector2(0, 1), "sight": 7, "off": Vector2(0, -64), "tint": Color(0.85, 0.72, 1.0)}],
				"A": [{"t": "audience", "rows": 5, "seats": 10, "face": Vector2(0, -1), "aisle": 0, "spacing": Vector2(36, 40), "wanderer": true}],
				"I": [{"t": "audience", "rows": 5, "seats": 10, "face": Vector2(0, -1), "aisle": 0, "spacing": Vector2(36, 40), "wanderer": false}],
				"J": [{"t": "audience", "rows": 4, "seats": 10, "face": Vector2(0, -1), "aisle": 0, "spacing": Vector2(36, 40), "wanderer": false}],
				"L": [{"t": "audience", "rows": 4, "seats": 10, "face": Vector2(0, -1), "aisle": 0, "spacing": Vector2(36, 40), "wanderer": false}],
				"T": [{"t": "trigger", "event": "platea", "size": Vector2(96, 32)}],
				"t": [{"t": "chest", "kind": "cassa", "item": "camomilla", "money": 60}],
				"*": [{"t": "prop", "kind": "riflettore"}],
			},
			"decor": [],
		},
		{
			"id": "fondo", "floor": "d", "ambient": Color(0.42, 0.36, 0.52), "dust": true,
			"rows": [
				"#################################",
				"#################################",
				"#################################",
				"#_______________X_______________#",
				"#1______________T_______________#",
				"#_______________@_______________#",
				"#EEEEEEEEEEEEEE===EEEEEEEEEEEEEE#",
				"#dddddddddddddd===dddddddddddddd#",
				"#ddAddddddddddd===dIdddddddddddd#",
				"#dddddddddddddd===dddddddddddddd#",
				"#dddddddddddddd===dddddddddddddd#",
				"#dddddddddddddd===dddddddddddddd#",
				"#dddddddddddddd===dddddddddddddd#",
				"#dddddddddddddd===dddddddddddddd#",
				"#dddddddddddddd===dddddddddddddd#",
				"#dddddddddddddd===dddddddddddddd#",
				"#dddddddddddddd===dddddddddddddd#",
				"#dddddddddddddd===dddddddddddddd#",
				"#dddddddddddddd===dddddddddddddd#",
				"#dddddddddddddd===dddddddddddddd#",
				"#dddddddddddddd===dddddddddddddd#",
				"#dddddddddddddd===dddddddddddddd#",
				"#dddddddddddddd===dddddddddddddd#",
				"#dddddddddddddd===dddddddddddddd#",
				"#dddddddddddddd=U=dddddddddddddd#",
				"#dddddddddddddd===dddddddddddddd#",
				"#ddddddddddddddd=ddddddddddddddd#",
				"################Y################",
			],
			"on": {"X": "_", "Y": "o", "1": "_"},
			"legend": {
				"X": [{"t": "prop", "kind": "porta_dipinta"}],
				"T": [{"t": "trigger", "event": "porta_dipinta", "size": Vector2(96, 32)}],
				"@": [{"t": "spawn", "id": "ingresso", "face": Vector2(0, -1)}],
				"A": [{"t": "audience", "rows": 7, "seats": 10, "face": Vector2(0, -1), "aisle": 0, "spacing": Vector2(36, 40), "wanderer": true}],
				"I": [{"t": "audience", "rows": 7, "seats": 10, "face": Vector2(0, -1), "aisle": 0, "spacing": Vector2(36, 40), "wanderer": false}],
				"U": [{"t": "trigger", "event": "ultima_fila", "size": Vector2(160, 32)}],
				"Y": [{"t": "prop", "kind": "porta_vera"}],
				"1": [{"t": "warp", "to": "auditorium", "spawn": "fondo", "size": Vector2(32, 32)}],
			},
			"decor": [],
		},
	]
